#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'PEDRO ICARO'
        hostname: RGN-00411-LTP
        username: pedro
        password: '$y$j9T$/cdKb2.w38nNCCQXmBFPc.$nuK5fTR4.CPAXPd0Y1wjnpQmk22SqHPkN1SsK4xZqC4'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    storage:
        layout:
            name: lvm
            password: "Watch0175%"
    packages:
        - wget
        - nano
        - git
        - htop
        - ubuntu-restricted-extras
        - linux-tools-generic
        - software-properties-common
        - python3-pip
        - default-jdk
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        updates: all

    late-commands:
      - curtin in-target -- apt-get update
      - curtin in-target -- apt-get install -y git python3 ca-certificates
      - curtin in-target -- bash -c "git clone https://github.com/TI-WATCH/ubuntu-autoinstall.git /opt/ubuntu-autoinstall"
      - curtin in-target -- bash -c "chmod +x /opt/ubuntu-autoinstall/setup_mdatp.sh"
      - curtin in-target -- bash -c "/opt/ubuntu-autoinstall/setup_mdatp.sh | tee /var/log/setup_mdatp.log"

    shutdown: reboot

